### ISSUE TITLE
How does it work in windows?

### ISSUE THREAD

**Issue by llcc** [novoid/Memacs#22]
I would like to give a fresh start on memacs.
But after i installed it, i have no idea how to use it.
I do not know how to configure it and execute it, and how to get the archive files.
Can you give me a little bit hint?

**Comment by novoid** [comment]
Hi!
I'm afraid that some parts of Memacs might not run only on Windows systems. Please report back if you find issues.

The basic principle with starting is: decide which Memacs-module you need and read its help page "bin/memacs-foobar --help". Then you manually design its command line parameters so that you get the desired Org-mode file result. If this is working, you can automate its invocation. However, this is quite a drag with Windows systems. I personally prefer using a Cygwin environment with cron daemon. YMMV.

Good luck and have fun with Memacs!
