### ISSUE TITLE
Update memacs package in pypi or update installation instructions

### ISSUE THREAD

**Issue by schvabodka-man** [novoid/Memacs#42]
Hello. The package in pypi is very old(2014) and don't have mumacs_mumail module. Ae there any plans on updating it? Or just update installation instructions, i'm getting 
```
File "./memacs_mumail.py", line 5, in <module>
    from memacs.mu import MuMail
ImportError: No module named memacs.mu
```
I'm not very savvy with python and idk how to install this dependency by hands.

**Comment by novoid** [comment]
Thanks for the reminder that Memacs/pip was *very* old. I just uploaded the current state as new pip package for you.

You can search for external dependencies using `pip search <keyword>` and install them using `pip install <packagename>`.

However, MuMail is no external dependency, it is implemented within memacs. It looks to me that you've got an issue with your Python path.

For testing purposes for a single call, you can use `PYTHONPATH="${HOME}/src/memacs/:${HOME}/src/memacs/memacs/" ${HOME}/src/memacs/bin/memacs_mumail.py` using your directory paths of course.

For setting your PYTHONPATH for the current shell session, you can do: `export PYTHONPATH="${HOME}/src/memacs/:${HOME}/src/memacs/memacs/"`

Put the export statement it in your shell startup file in order to make it permanent.
