### ISSUE TITLE
Confusion about stub and archive files

### ISSUE THREAD

**Issue by fullofcaffeine** [novoid/Memacs#85]
First of all, thanks for Memacs! I've been using it for Twitter favorites (adapting the original Twitter module, inheriting from the same `Memacs` base class) and it has been working great so far. I might share the module after I figure out the following:

The generated file (the `-o` option when calling the module from the CLI), has the following in header text:

```
## To add this file to your org-agenda files open the stub file  (file.org) not this file(file.org_archive) with emacs and do following: M-x org-agenda-file-to-front
``` 

I'm confused though. First, when calling my module, I call it the following way:

```
python /home/fullofcaffeine/workspace/code/Memacs/bin/memacs_twitter_favorites.py -c ~/memacs.ini -o ~/caffeine/org/wiki/memacs/Twitter.org
``` 
That text seems to imply that the generated file *is* the archive file, why? Also I can't find any correspondent auto-generated `Twitter.org_archive` file. Also, what is the "stub" file and what is it supposed to contain? I also don't see the correspondent `archive` file anywhere.

Am I missing something?

Thanks in advance!

**Comment by novoid** [comment]
Hi coffee junkie ;-)

I see the source for your confusion.

In the FAQs https://github.com/novoid/Memacs/blob/master/docs/FAQs_and_Best_Practices.org#file-names-of-generated-memacs-files-archive I am trying to explain the reason why you most likely don't want to generate `Twitter.org` but `Twitter.org_archive` instead.

Archiving is a standard feature of Org mode: https://orgmode.org/manual/Moving-subtrees.html#Moving-subtrees

This way, you can keep your `.org` files small and clean: moving content to `.org_archive` files offers the possibility to keep the content somewhere but it doesn't interfere with your daily tasks or agenda. With a decent number of headings in your Memacs files, you will end up having performance issues as described in the FAQs. As a consequence, I recommend generating content into archive files. In order to see this content in your agenda, you then need more or less empty files without the `_archive` extension which I called stub files.

Does this now make more sense to you?
