### ISSUE TITLE
Browser extension: WorldBrain's Memex

### ISSUE THREAD

**Issue by DynamicMetaFlow** [novoid/Memacs#88]
Greetings! 

After coming across this extension I thought about sharing what I've learned here for others if this seems unrelated, or pitching a software project please feel free to close this issue. 

Yesterday I came across a browser extension from [WorldBrain](https://worldbrain.io/) called [Memex](https://github.com/WorldBrain/Memex), it's inspired by Vannevar Bush's vision of a Memex.  

After doing some initial digging around, I learned data generated using the extension could be exported locally to a JSON format. Upon learning this, I was curious about the possibilities of using this extension and its features and using a memacs module to create an org-file to view the information in emacs.

Some of its features include:
- Full-Text Search in Web History & Bookmarks:
Search with every word of all websites & PDFs you visited & filter by time, domain, tags or bookmarks

- Web Annotations:
Add notes to websites and pieces of text in them

- Blazing fast and flexible organization
Add bookmarks, tags or sort websites into lists on the fly. 

If anyone has used the extension already or has thoughts about the extension I would love to hear them! Thank you for your time.

**Comment by novoid** [comment]
Hi Alex,
This really looks like a neat piece of software.
Since this is no "issue", I'll close it here and add a "Related Projects" section to the readme file. 

My personal thoughts without testing it: although the featureset sounds awesome, I dislike the additional fragmentation. Looking for content should be doable in one spot. With the mentioned software, I'd have to search in my desktop search and then again in the browser extension.
I once used a Firefox extension http://shelve.sourceforge.net/ which saved all visited web pages into files that got indexed by my filenametimestamps-module. This was very helpful because I got full text search in my desktop search engine for all visited web pages. Unfortunately, shelve stopped working with the latest Firefox add-on changes. I do not have a replacement for it yet.
